## <strong>2. NumPy: Universal Functions (UFunc)</strong>

In [1]:
import numpy as np

In [5]:
# 역수 계산 함수
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

# [+] 함수 테스트
compute_reciprocals([1, 3, 5, 9, 3])

array([1.        , 0.33333333, 0.2       , 0.11111111, 0.33333333])

#### <strong>역수 계산: Python loop vs NumPy ufuncs</strong>
+ ```%timeit```: 셀 단위 코드 실행 시간을 측정하는 매직 함수

In [6]:
# [+] 백만 개 크기의 난수 배열 생성: 정수, 값 범위 [1, 100)
big_arr = np.random.randint(1, 100, size=1000000)
big_arr

array([56, 85, 30, ..., 41, 32, 86])

In [9]:
%%timeit #시간측정 함수(매직함수) / 주피터랩에서 제공, 파이썬 기본제공X 반복실행에서 평균시간 출력


# [+] Python loop를 통한 역수 계산 
compute_reciprocals(big_arr)

2.14 s ± 291 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
%%timeit

# [+] NumPy ufunc을 통한 벡터화된 역수 계산
1 / big_arr

4.23 ms ± 723 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### <strong>유니버설 함수들</strong>

In [14]:
# 난수 배열 2개 생성
np.random.seed(1)
arr1 = np.random.randint(10, size=5)
arr2 = np.random.randint(10, size=5)

print(arr1, arr2)

[5 8 9 5 0] [0 1 7 6 9]


In [15]:
# 배열-스칼라 연산
arr1 = arr1 - 2
print(arr1)

[ 3  6  7  3 -2]


In [16]:
# 배열-배열 연산
arr3 = arr1 + arr2
print(arr3)

[ 3  7 14  9  7]


In [18]:
# 다차원 배열 연산: 2차원 배열 ** 스칼라
arr4 = np.random.randint(10, size=(3, 5))
print(arr4)
print()
arr5 = arr4 ** 2
print(arr5)

[[9 7 6 9 1]
 [0 1 8 8 3]
 [9 8 7 3 6]]

[[81 49 36 81  1]
 [ 0  1 64 64  9]
 [81 64 49  9 36]]


In [20]:
"""
    UFuncs: 산술 연산
"""

# 기본 산술 연산
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x ** 2 =", x ** 2)

# 산술 연산에 대응하는 유니버설 함수
print("x + 5 =", np.add(x, 5))
print("x - 5 =", np.subtract(x, 5))
print("x * 2 =", np.multiply(x, 2))
print("x / 2 =", np.divide(x, 2))
print("x ** 2 =", np.power(x, 2))


x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x ** 2 = [0 1 4 9]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x ** 2 = [0 1 4 9]


In [22]:
"""
    UFuncs: 절댓값 계산
"""

# [+] 절댓값 함수
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [26]:
"""
    np.linspace(start, stop, num): 선형 간격 벡터 생성
        - start: 벡터의 시작 값
        - end: 벡터의 종료 값
        - num: 생성할 값의 개수
"""

# [+][0, 100]의 범위를 가지며, 균일한 간격의 5개의 값들로 구성되는 벡터를 생성
x = np.linspace(0, 100, 5)
x

array([  0.,  25.,  50.,  75., 100.])

In [30]:
# [+] [0, 100]의 범위를 가지며, [0, 10, 20, 30, ..., 100]와
# 같은 값들로 구성되는 벡터를 생성
x = np.linspace(0, 100, 11)
x

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [31]:
# 삼각함수(trigonometric functions)
theta = np.linspace(0, np.pi, 3)

print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [32]:
"""
    집계 함수: reduce()
"""

# 배열 생성
x = np.arange(1, 5)
x

array([1, 2, 3, 4])

In [36]:
# [+] 덧셈 연산으로 집계
aggr = np.add.reduce(x)
aggr

10

In [37]:
# [+] 곱셈 연산으로 집계
aggr = np.multiply.reduce(x)
aggr

24

In [39]:
"""
    집계 함수: accumulate()
"""

# [+] 덧셈 연산으로 집계
accum = np.add.accumulate(x)
accum

array([ 1,  3,  6, 10])

In [41]:
# [+] 곱셈 연산으로 집계
accum = np.multiply.accumulate(x)
accum

array([ 1,  2,  6, 24])

In [80]:
# 집계 함수: sum()
np.random.seed(5) #랜덤시드 for 재현성
arr = np.random.rand(1000000) # [+] 0~1 사이의 실수 형태의 난수 배열 생성

print(arr)
print("sum =", np.sum(arr))

[0.22199317 0.87073231 0.20671916 ... 0.33788134 0.54326796 0.69431429]
sum = 500432.71282747824


In [71]:
# sum(): Python 내장함수
%timeit sum(arr)

89.7 ms ± 5.67 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [72]:
# np.sum()
%timeit np.sum(arr) # 1000µs = 1ms

499 μs ± 30.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [87]:
# [+] 그 외의 집계함수
print("max =", np.max(arr))
print("min =", np.min(arr))
print("mean =", np.mean(arr))
print("median =", np.median(arr))
print("percentile =", np.percentile(arr, 90))
print("variance =", np.var(arr))
print("standard deviation =", np.std(arr))
print("index of maximum value =", np.argmax(arr))
print("index of minimum value =", np.argmin(arr))
print("Is there any number greater than 1? =", np.any(arr>1))
print("Is every number greater than 0? =", np.all(arr>0)) 

max = 0.9999975281394899
min = 1.2032035381359663e-06
mean = 0.5004327128274783
median = 0.5000909446902552
percentile = 0.9001474727982709
variance = 0.08324867093756745
standard deviation = 0.2885284577603524
index of maximum value = 385290
index of minimum value = 80566
Is there any number greater than 1? = False
Is every number greater than 0? = True


In [88]:
"""다차원 집계"""

# 2차원 난수 배열 생성
np.random.seed(0)
arr = np.random.randint(10, size=(3, 4))
arr

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [89]:
# [+] 행 방향으로 집계 (row sum)
np.sum(arr, axis = 0)

array([14, 13, 13, 14])

In [90]:
# [+] 열 방향으로 집계 (column sum)
np.sum(arr, axis = 1)

array([11, 24, 19])